#!/usr/bin/env python3
"""生成 optimization_progress.md - 跨对话/跨智能体的优化进度追踪文件"""

def main():
    lines = []
    lines.append("# 占位实现优化进度\n")
    lines.append("> 这是一个**自包含的进度文件**，用于跨对话/跨智能体追踪优化进度。")
    lines.append("> 每次完成一项后，将 `[ ]` 改为 `[x]` 并更新 `当前进度` 和 `最后完成`。\n")
    lines.append("---\n")
    lines.append("## 元信息\n")
    lines.append("- **总待优化项**: 313")
    lines.append("- **当前进度**: 0/313 (0.0%)")
    lines.append("- **最后完成**: (无)")
    lines.append("- **当前阶段**: 1 - 基础设施与核心系统\n")

    # 所有条目
    entries = []

    def add(num, name, cat, path):
        entries.append((num, name, cat, path))

    # 阶段1
    add(1, "Randommer", "核心工具", "Content/Randommer.cs")
    add(2, "VerminLordModSystem", "ModSystem", "Content/VerminLordModSystem.cs")
    add(3, "YuanSCurrency", "货币", "Content/Currencies/YuanSCurrency.cs")
    add(4, "OneStarbuff ~ FiveStarbuff", "Buffs", "Content/Buffs/AddToSelf/Pobuff/")
    add(5, "YanTongbuff", "Buffs", "Content/Buffs/AddToSelf/Pobuff/YanTongbuff.cs")
    add(6, "QingMaoDroplet + 背景/瀑布", "Biomes", "Content/Biomes/")

    # 阶段2a - Seeds
    add(7, "SpiritGrassSeed", "Seeds", "Content/Items/Seeds/SpiritGrassSeed.cs")
    add(8, "HealingHerbSeed", "Seeds", "Content/Items/Seeds/HealingHerbSeed.cs")
    add(9, "QiHerbSeed", "Seeds", "Content/Items/Seeds/QiHerbSeed.cs")
    add(10, "PoisonWeedSeed", "Seeds", "Content/Items/Seeds/PoisonWeedSeed.cs")
    add(11, "MoonOrchidSeed", "Seeds", "Content/Items/Seeds/MoonOrchidSeed.cs")
    add(12, "RiceBagGrassSeed", "Seeds", "Content/Items/Seeds/RiceBagGrassSeed.cs")
    add(13, "WineGourdFlowerSeed", "Seeds", "Content/Items/Seeds/WineGourdFlowerSeed.cs")
    add(14, "SpearBambooSeed", "Seeds", "Content/Items/Seeds/SpearBambooSeed.cs")
    add(15, "BoneBanbooSeed", "Seeds", "Content/Items/Seeds/BoneBanbooSeed.cs")
    add(16, "SpiritSpringPlantSeed", "Seeds", "Content/Items/Seeds/SpiritSpringPlantSeed.cs")

    # 阶段2b - Banners
    add(17, "BladeBloodBatGuBanner", "Banners", "Content/Items/Placeable/Banners/BladeBloodBatGuBanner.cs")
    add(18, "LegionAntBanner", "Banners", "Content/Items/Placeable/Banners/LegionAntBanner.cs")
    add(19, "StrongElectricWolfBanner", "Banners", "Content/Items/Placeable/Banners/StrongElectricWolfBanner.cs")

    # 阶段2c - Tokens
    add(20, "交易令", "Tokens", "Content/Items/Tokens/交易令.cs")
    add(21, "令牌信物", "Tokens", "Content/Items/Tokens/令牌信物.cs")
    add(22, "来客令", "Tokens", "Content/Items/Tokens/来客令.cs")
    add(23, "琉璃楼主令", "Tokens", "Content/Items/Tokens/琉璃楼主令.cs")
    add(24, "紫荆令牌", "Tokens", "Content/Items/Tokens/紫荆令牌.cs")
    add(25, "通缉令", "Tokens", "Content/Items/Tokens/通缉令.cs")
    add(26, "铁家令牌", "Tokens", "Content/Items/Tokens/铁家令牌.cs")
    add(27, "铭牌", "Tokens", "Content/Items/Tokens/铭牌.cs")

    # 阶段2d - Books
    add(28, "乾坤晶壁雏形", "Books", "Content/Items/Books/乾坤晶壁雏形.cs")
    add(29, "兽皮地图", "Books", "Content/Items/Books/兽皮地图.cs")
    add(30, "黑白颠倒云", "Books", "Content/Items/Books/黑白颠倒云.cs")

    # 阶段2e - Equipment
    add(31, "真绸", "Equipment", "Content/Items/Equipment/真绸.cs")

    # 阶段3a - Breeding
    add(32, "GuBox", "Breeding", "Content/Items/Breeding/GuBox.cs")
    add(33, "SpiritPoolBox", "Breeding", "Content/Items/Breeding/SpiritPoolBox.cs")
    add(34, "AncestralAltar", "Breeding", "Content/Items/Breeding/AncestralAltar.cs")
    add(35, "BattleArena", "Breeding", "Content/Items/Breeding/BattleArena.cs")

    # 阶段3b - Consumables
    add(36, "GuFoodPellet", "Consumables", "Content/Items/Consumables/GuFoodPellet.cs")
    add(37, "SpiritMeat", "Consumables", "Content/Items/Consumables/SpiritMeat.cs")
    add(38, "BloodEssence", "Consumables", "Content/Items/Consumables/BloodEssence.cs")
    add(39, "TenLifeGu", "Consumables", "Content/Items/Consumables/TenLifeGu.cs")
    add(40, "HundredLifeGu", "Consumables", "Content/Items/Consumables/HundredLifeGu.cs")
    add(41, "ThousandLifeGu", "Consumables", "Content/Items/Consumables/ThousandLifeGu.cs")
    add(42, "DragonBallCricket", "Consumables", "Content/Items/Consumables/DragonBallCricket.cs")
    add(43, "FlowerPig", "Consumables", "Content/Items/Consumables/FlowerPig.cs")
    add(44, "StrengthLongicorn", "Consumables", "Content/Items/Consumables/StrengthLongicorn.cs")
    add(45, "JunLiGu", "Consumables", "Content/Items/Consumables/JunLiGu.cs")
    add(46, "ShiJunLiGu", "Consumables", "Content/Items/Consumables/ShiJunLiGu.cs")
    add(47, "ShiJinLiGu", "Consumables", "Content/Items/Consumables/ShiJinLiGu.cs")

    # 阶段4 - GuYueArchitecture
    add(48, "SpiritSpring", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/SpiritSpring.cs")
    add(49, "HealingHerb", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/HealingHerb.cs")
    add(50, "QiHerb", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/QiHerb.cs")
    add(51, "PoisonWeed", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/PoisonWeed.cs")
    add(52, "MoonOrchid", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/MoonOrchid.cs")
    add(53, "RiceBagGrass", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/RiceBagGrass.cs")
    add(54, "WineGourdFlower", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/WineGourdFlower.cs")
    add(55, "SpearBamboo", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/SpearBamboo.cs")
    add(56, "GreenBambooWineJar", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/GreenBambooWineJar.cs")
    add(57, "DragonCricketJar", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/DragonCricketJar.cs")
    add(58, "GlowingStalactite", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/GlowingStalactite.cs")
    add(59, "RedCopperIncenseBurner", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/RedCopperIncenseBurner.cs")
    add(60, "AncestorTablet", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/AncestorTablet.cs")
    add(61, "BlackLacquerAltar", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/BlackLacquerAltar.cs")
    add(62, "BrownYellowFloor", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/BrownYellowFloor.cs")
    add(63, "SchoolDesk", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/SchoolDesk.cs")
    add(64, "StiltedHouse", "GuYueArchitecture", "Content/Items/Placeable/GuYueArchitecture/StiltedHouse.cs")

    # 阶段5 - Recipes
    add(65, "人祖传", "Recipes", "Content/Items/Recipes/人祖传.cs")
    add(66, "传承印记", "Recipes", "Content/Items/Recipes/传承印记.cs")
    add(67, "天难真传", "Recipes", "Content/Items/Recipes/天难真传.cs")
    add(68, "白骨秘方", "Recipes", "Content/Items/Recipes/白骨秘方.cs")
    add(69, "灰骨巨书", "Recipes", "Content/Items/Recipes/灰骨巨书.cs")
    add(70, "灰白石板", "Recipes", "Content/Items/Recipes/灰白石板.cs")
    add(71, "第十三座鹰巢", "Recipes", "Content/Items/Recipes/第十三座鹰巢.cs")

    # 阶段6 - Prefixes
    add(72, "ActivePrefix", "Prefixes", "Content/Prefixes/ActivePrefix.cs")
    add(73, "AutismPrefix", "Prefixes", "Content/Prefixes/AutismPrefix.cs")
    add(74, "ColeopteraPrefix", "Prefixes", "Content/Prefixes/ColeopteraPrefix.cs")
    add(75, "CurlingUpPrefix", "Prefixes", "Content/Prefixes/CurlingUpPrefix.cs")
    add(76, "DyingPrefix", "Prefixes", "Content/Prefixes/DyingPrefix.cs")
    add(77, "ExtroversionPrefix", "Prefixes", "Content/Prefixes/ExtroversionPrefix.cs")
    add(78, "IntrovertPrefix", "Prefixes", "Content/Prefixes/IntrovertPrefix.cs")
    add(79, "MildPrefix", "Prefixes", "Content/Prefixes/MildPrefix.cs")
    add(80, "SharpClawPrefix", "Prefixes", "Content/Prefixes/SharpClawPrefix.cs")
    add(81, "SharpTeethPrefix", "Prefixes", "Content/Prefixes/SharpTeethPrefix.cs")
    add(82, "ShyPrefix", "Prefixes", "Content/Prefixes/ShyPrefix.cs")
    add(83, "StretchPrefix", "Prefixes", "Content/Prefixes/StretchPrefix.cs")

    # 阶段7 - Daos
    add(84, "PowerWeapon", "力", "Content/Items/Weapons/Daos/PowerWeapon.cs")
    add(85, "WaterWeapon", "水", "Content/Items/Weapons/Daos/WaterWeapon.cs")
    add(86, "FireWeapon", "火", "Content/Items/Weapons/Daos/FireWeapon.cs")
    add(87, "WoodWeapon", "木", "Content/Items/Weapons/Daos/WoodWeapon.cs")
    add(88, "StarWeapon", "星", "Content/Items/Weapons/Daos/StarWeapon.cs")
    add(89, "MudWeapon", "土", "Content/Items/Weapons/Daos/MudWeapon.cs")
    add(90, "EatingWeapon", "食", "Content/Items/Weapons/Daos/EatingWeapon.cs")
    add(91, "WindWeapon", "风", "Content/Items/Weapons/Daos/WindWeapon.cs")
    add(92, "LightningWeapon", "雷", "Content/Items/Weapons/Daos/LightningWeapon.cs")
    add(93, "IceSnowWeapon", "冰雪", "Content/Items/Weapons/Daos/IceSnowWeapon.cs")
    add(94, "SwordWeapon", "剑", "Content/Items/Weapons/Daos/SwordWeapon.cs")
    add(95, "SoulWeapon", "魂", "Content/Items/Weapons/Daos/SoulWeapon.cs")
    add(96, "GoldWeapon", "金", "Content/Items/Weapons/Daos/GoldWeapon.cs")
    add(97, "DarkWeapon", "暗", "Content/Items/Weapons/Daos/DarkWeapon.cs")
    add(98, "LightWeapon", "光", "Content/Items/Weapons/Daos/LightWeapon.cs")
    add(99, "PoisonWeapon", "毒", "Content/Items/Weapons/Daos/PoisonWeapon.cs")
    add(100, "BloodWeapon", "血", "Content/Items/Weapons/Daos/BloodWeapon.cs")
    add(101, "BoneWeapon", "骨", "Content/Items/Weapons/Daos/BoneWeapon.cs")
    add(102, "MoonWeapon", "月", "Content/Items/Weapons/Daos/MoonWeapon.cs")
    add(103, "CloudWeapon", "云", "Content/Items/Weapons/Daos/CloudWeapon.cs")
    add(104, "ShadowWeapon", "影", "Content/Items/Weapons/Daos/ShadowWeapon.cs")
    add(105, "QiWeapon", "气", "Content/Items/Weapons/Daos/QiWeapon.cs")
    add(106, "SkyWeapon", "天", "Content/Items/Weapons/Daos/SkyWeapon.cs")
    add(107, "TimeWeapon", "时间", "Content/Items/Weapons/Daos/TimeWeapon.cs")
    add(108, "SpaceWeapon", "空间", "Content/Items/Weapons/Daos/SpaceWeapon.cs")
    add(109, "VoidWeapon", "虚空", "Content/Items/Weapons/Daos/VoidWeapon.cs")
    add(110, "LifeDeathWeapon", "生死", "Content/Items/Weapons/Daos/LifeDeathWeapon.cs")
    add(111, "YinYangWeapon", "阴阳", "Content/Items/Weapons/Daos/YinYangWeapon.cs")
    add(112, "DreamWeapon", "梦", "Content/Items/Weapons/Daos/DreamWeapon.cs")
    add(113, "WisdomWeapon", "智", "Content/Items/Weapons/Daos/WisdomWeapon.cs")
    add(114, "LuckWeapon", "运", "Content/Items/Weapons/Daos/LuckWeapon.cs")
    add(115, "RuleWeapon", "律", "Content/Items/Weapons/Daos/RuleWeapon.cs")
    add(116, "WarWeapon", "战", "Content/Items/Weapons/Daos/WarWeapon.cs")
    add(117, "KillingWeapon", "杀", "Content/Items/Weapons/Daos/KillingWeapon.cs")
    add(118, "SlaveWeapon", "奴", "Content/Items/Weapons/Daos/SlaveWeapon.cs")
    add(119, "LoveWeapon", "爱", "Content/Items/Weapons/Daos/LoveWeapon.cs")
    add(120, "VoiceWeapon", "音", "Content/Items/Weapons/Daos/VoiceWeapon.cs")
    add(121, "PersonWeapon", "人", "Content/Items/Weapons/Daos/PersonWeapon.cs")
    add(122, "FlyingWeapon", "飞", "Content/Items/Weapons/Daos/FlyingWeapon.cs")
    add(123, "StealingWeapon", "偷", "Content/Items/Weapons/Daos/StealingWeapon.cs")
    add(124, "VariationWeapon", "变化", "Content/Items/Weapons/Daos/VariationWeapon.cs")
    add(125, "UnrealWeapon", "虚幻", "Content/Items/Weapons/Daos/UnrealWeapon.cs")
    add(126, "InfoWeapon", "信息", "Content/Items/Weapons/Daos/InfoWeapon.cs")
    add(127, "CharmWeapon", "媚", "Content/Items/Weapons/Daos/CharmWeapon.cs")
    add(128, "KnifeWeapon", "刀", "Content/Items/Weapons/Daos/KnifeWeapon.cs")
    add(129, "TacticalWeapon", "战术", "Content/Items/Weapons/Daos/TacticalWeapon.cs")
    add(130, "DrawWeapon", "画", "Content/Items/Weapons/Daos/DrawWeapon.cs")
    add(131, "PractiseWeapon", "修炼", "Content/Items/Weapons/Daos/PractiseWeapon.cs")
    add(132, "PelletWeapon", "丸", "Content/Items/Weapons/Daos/PelletWeapon.cs")
    add(133, "BanWeapon", "ban", "Content/Items/Weapons/Daos/BanWeapon.cs")
    add(134, "SuccessFailureWeapon", "成败", "Content/Items/Weapons/Daos/SuccessFailureWeapon.cs")

    # 阶段8a - 核心材料
    add(135, "仙元石", "Materials", "Content/Items/Materials/仙元石.cs")
    add(136, "天晶", "Materials", "Content/Items/Materials/天晶.cs")
    add(137, "金精", "Materials", "Content/Items/Materials/金精.cs")
    add(138, "地煞粉", "Materials", "Content/Items/Materials/地煞粉.cs")
    add(139, "裂天粉", "Materials", "Content/Items/Materials/裂天粉.cs")
    add(140, "星辰石", "Materials", "Content/Items/Materials/星辰石.cs")
    add(141, "紫金石", "Materials", "Content/Items/Materials/紫金石.cs")
    add(142, "紫金化石", "Materials", "Content/Items/Materials/紫金化石.cs")
    add(143, "赤练金", "Materials", "Content/Items/Materials/赤练金.cs")
    add(144, "霸铜", "Materials", "Content/Items/Materials/霸铜.cs")
    add(145, "正天银", "Materials", "Content/Items/Materials/正天银.cs")
    add(146, "黑油", "Materials", "Content/Items/Materials/黑油.cs")
    add(147, "黑金铠甲", "Materials", "Content/Items/Materials/黑金铠甲.cs")
    add(148, "暗流金钢", "Materials", "Content/Items/Materials/暗流金钢.cs")
    add(149, "青铜面具", "Materials", "Content/Items/Materials/青铜面具.cs")
    add(150, "无常石", "Materials", "Content/Items/Materials/无常石.cs")
    add(151, "火炭石", "Materials", "Content/Items/Materials/火炭石.cs")
    add(152, "炎鸿石", "Materials", "Content/Items/Materials/炎鸿石.cs")
    add(153, "物品寒玉", "Materials", "Content/Items/Materials/物品寒玉.cs")
    add(154, "珍珠土", "Materials", "Content/Items/Materials/珍珠土.cs")

    # 阶段8b - 生物材料
    add(155, "万目大明牛", "Materials", "Content/Items/Materials/万目大明牛.cs")
    add(156, "九宫鹤", "Materials", "Content/Items/Materials/九宫鹤.cs")
    add(157, "九子龙图", "Materials", "Content/Items/Materials/九子龙图.cs")
    add(158, "六头大蛇黑血", "Materials", "Content/Items/Materials/六头大蛇黑血.cs")
    add(159, "军团蚁", "Materials", "Content/Items/Materials/军团蚁.cs")
    add(160, "刺脊星龙鱼", "Materials", "Content/Items/Materials/刺脊星龙鱼.cs")
    add(161, "合鸣鹰", "Materials", "Content/Items/Materials/合鸣鹰.cs")
    add(162, "夜狼皇", "Materials", "Content/Items/Materials/夜狼皇.cs")
    add(163, "小箭尾雕", "Materials", "Content/Items/Materials/小箭尾雕.cs")
    add(164, "巨音贝", "Materials", "Content/Items/Materials/巨音贝.cs")
    add(165, "幽火龙蟒", "Materials", "Content/Items/Materials/幽火龙蟒.cs")
    add(166, "斑虎蜜蜂蜂翅", "Materials", "Content/Items/Materials/斑虎蜜蜂蜂翅.cs")
    add(167, "板栗牦牛", "Materials", "Content/Items/Materials/板栗牦牛.cs")
    add(168, "混天鹰", "Materials", "Content/Items/Materials/混天鹰.cs")
    add(169, "追虹鹰", "Materials", "Content/Items/Materials/追虹鹰.cs")
    add(170, "铁冠鹰", "Materials", "Content/Items/Materials/铁冠鹰.cs")
    add(171, "铁喙飞鹤", "Materials", "Content/Items/Materials/铁喙飞鹤.cs")
    add(172, "风狼王", "Materials", "Content/Items/Materials/风狼王.cs")
    add(173, "马群", "Materials", "Content/Items/Materials/马群.cs")
    add(174, "黄玉狮子", "Materials", "Content/Items/Materials/黄玉狮子.cs")
    add(175, "鸡年兽", "Materials", "Content/Items/Materials/鸡年兽.cs")
    add(176, "长恨蛛", "Materials", "Content/Items/Materials/长恨蛛.cs")
    add(177, "附天菌", "Materials", "Content/Items/Materials/附天菌.cs")
    add(178, "雪莲花精", "Materials", "Content/Items/Materials/雪莲花精.cs")
    add(179, "青矛竹", "Materials", "Content/Items/Materials/青矛竹.cs")
    add(180, "骨刺", "Materials", "Content/Items/Materials/骨刺.cs")
    add(181, "鬼嘤音", "Materials", "Content/Items/Materials/鬼嘤音.cs")
    add(182, "魅蓝电影", "Materials", "Content/Items/Materials/魅蓝电影.cs")
    add(183, "天龙完整骨骼", "Materials", "Content/Items/Materials/天龙完整骨骼.cs")
    add(184, "走肉树", "Materials", "Content/Items/Materials/走肉树.cs")

    # 阶段8c - 鱼材料
    add(185, "散文鲤", "Materials", "Content/Items/Materials/散文鲤.cs")
    add(186, "金龙鱼", "Materials", "Content/Items/Materials/金龙鱼.cs")
    add(187, "银龙鱼", "Materials", "Content/Items/Materials/银龙鱼.cs")
    add(188, "铜龙鱼", "Materials", "Content/Items/Materials/铜龙鱼.cs")
    add(189, "铁龙鱼", "Materials", "Content/Items/Materials/铁龙鱼.cs")
    add(190, "真武鲤", "Materials", "Content/Items/Materials/真武鲤.cs")
    add(191, "物品龙鱼", "Materials", "Content/Items/Materials/物品龙鱼.cs")
    add(192, "物品龙鳞土", "Materials", "Content/Items/Materials/物品龙鳞土.cs")
    add(193, "珠线水", "Materials", "Content/Items/Materials/珠线水.cs")
    add(194, "水核", "Materials", "Content/Items/Materials/水核.cs")

    # 阶段8d - 植物材料
    add(195, "地老木", "Materials", "Content/Items/Materials/地老木.cs")
    add(196, "缘木", "Materials", "Content/Items/Materials/缘木.cs")
    add(197, "月兰花", "Materials", "Content/Items/Materials/月兰花.cs")
    add(198, "斑斓霸王花", "Materials", "Content/Items/Materials/斑斓霸王花.cs")
    add(199, "脉轮瓜", "Materials", "Content/Items/Materials/脉轮瓜.cs")
    add(200, "气功果核", "Materials", "Content/Items/Materials/气功果核.cs")
    add(201, "物品神鹿果", "Materials", "Content/Items/Materials/物品神鹿果.cs")
    add(202, "流光果", "Materials", "Content/Items/Materials/流光果.cs")
    add(203, "石猴毫毛", "Materials", "Content/Items/Materials/石猴毫毛.cs")
    add(204, "星夜黏涎", "Materials", "Content/Items/Materials/星夜黏涎.cs")
    add(205, "星意", "Materials", "Content/Items/Materials/星意.cs")
    add(206, "心境", "Materials", "Content/Items/Materials/心境.cs")
    add(207, "天露", "Materials", "Content/Items/Materials/天露.cs")
    add(208, "天柱风", "Materials", "Content/Items/Materials/天柱风.cs")
    add(209, "六声茶", "Materials", "Content/Items/Materials/六声茶.cs")

    # 阶段8e - 建筑材料
    add(210, "中央大殿", "Materials", "Content/Items/Materials/中央大殿.cs")
    add(211, "五光山", "Materials", "Content/Items/Materials/五光山.cs")
    add(212, "五相赌斗门", "Materials", "Content/Items/Materials/五相赌斗门.cs")
    add(213, "人海雏形", "Materials", "Content/Items/Materials/人海雏形.cs")
    add(214, "血海雏形", "Materials", "Content/Items/Materials/血海雏形.cs")
    add(215, "炼道大阵", "Materials", "Content/Items/Materials/炼道大阵.cs")
    add(216, "超级仙阵", "Materials", "Content/Items/Materials/超级仙阵.cs")
    add(217, "金晓大殿", "Materials", "Content/Items/Materials/金晓大殿.cs")
    add(218, "镇魔塔", "Materials", "Content/Items/Materials/镇魔塔.cs")
    add(219, "眠云棺椁", "Materials", "Content/Items/Materials/眠云棺椁.cs")
    add(220, "棺材", "Materials", "Content/Items/Materials/棺材.cs")
    add(221, "飞沙地洞", "Materials", "Content/Items/Materials/飞沙地洞.cs")
    add(222, "漂游炼巢", "Materials", "Content/Items/Materials/漂游炼巢.cs")
    add(223, "功德方尖碑", "Materials", "Content/Items/Materials/功德方尖碑.cs")
    add(224, "市井", "Materials", "Content/Items/Materials/市井.cs")

    # 阶段8f - 榜单材料
    add(225, "任务榜", "Materials", "Content/Items/Materials/任务榜.cs")
    add(226, "兑换榜", "Materials", "Content/Items/Materials/兑换榜.cs")
    add(227, "战功榜", "Materials", "Content/Items/Materials/战功榜.cs")
    add(228, "贡献榜", "Materials", "Content/Items/Materials/贡献榜.cs")
    add(229, "光明华轮火", "Materials", "Content/Items/Materials/光明华轮火.cs")
    add(230, "乾清一气", "Materials", "Content/Items/Materials/乾清一气.cs")
    add(231, "青玉风流", "Materials", "Content/Items/Materials/青玉风流.cs")

    # 阶段8g - 杂项材料
    add(232, "怨气泥人", "Materials", "Content/Items/Materials/怨气泥人.cs")
    add(233, "红莲鬼脸", "Materials", "Content/Items/Materials/红莲鬼脸.cs")
    add(234, "宠心", "Materials", "Content/Items/Materials/宠心.cs")
    add(235, "法眼血", "Materials", "Content/Items/Materials/法眼血.cs")
    add(236, "泥沼蟹", "Materials", "Content/Items/Materials/泥沼蟹.cs")
    add(237, "涛声依旧", "Materials", "Content/Items/Materials/涛声依旧.cs")
    add(238, "饮刃酒", "Materials", "Content/Items/Materials/饮刃酒.cs")
    add(239, "孪生冰心", "Materials", "Content/Items/Materials/孪生冰心.cs")
    add(240, "地极天罡", "Materials", "Content/Items/Materials/地极天罡.cs")

    # 阶段9a - 仙蛊屋
    add(241, "仙蛊屋雏形", "Special", "Content/Items/Special/仙蛊屋雏形.cs")
    add(242, "仙蛊屋黑牢", "Special", "Content/Items/Special/仙蛊屋黑牢.cs")
    add(243, "凡草屋", "Special", "Content/Items/Special/凡草屋.cs")
    add(244, "茅草屋", "Special", "Content/Items/Special/茅草屋.cs")
    add(245, "方寸山", "Special", "Content/Items/Special/方寸山.cs")
    add(246, "羽圣城", "Special", "Content/Items/Special/羽圣城.cs")
    add(247, "龙宫", "Special", "Content/Items/Special/龙宫.cs")
    add(248, "豆神宫", "Special", "Content/Items/Special/豆神宫.cs")
    add(249, "万象宫殿", "Special", "Content/Items/Special/万象宫殿.cs")
    add(250, "万岁楼", "Special", "Content/Items/Special/万岁楼.cs")
    add(251, "星宿棋盘", "Special", "Content/Items/Special/星宿棋盘.cs")
    add(252, "劫运坛", "Special", "Content/Items/Special/劫运坛.cs")
    add(253, "煮运锅", "Special", "Content/Items/Special/煮运锅.cs")
    add(254, "恒舟", "Special", "Content/Items/Special/恒舟.cs")
    add(255, "肝命仙蛊屋", "Special", "Content/Items/Special/肝命仙蛊屋.cs")
    add(256, "安土重山堡", "Special", "Content/Items/Special/安土重山堡.cs")
    add(257, "玉清滴风小竹楼", "Special", "Content/Items/Special/玉清滴风小竹楼.cs")
    add(258, "太宇寺", "Special", "Content/Items/Special/太宇寺.cs")
    add(259, "镇魂殿", "Special", "Content/Items/Special/镇魂殿.cs")
    add(260, "贼巢", "Special", "Content/Items/Special/贼巢.cs")

    # 阶段9b - 亭台楼阁
    add(261, "一缺抱憾亭", "Special", "Content/Items/Special/一缺抱憾亭.cs")
    add(262, "今古亭", "Special", "Content/Items/Special/今古亭.cs")
    add(263, "松鹤亭", "Special", "Content/Items/Special/松鹤亭.cs")
    add(264, "搬拦亭", "Special", "Content/Items/Special/搬拦亭.cs")
    add(265, "刹那台", "Special", "Content/Items/Special/刹那台.cs")
    add(266, "日月观", "Special", "Content/Items/Special/日月观.cs")
    add(267, "海角阁", "Special", "Content/Items/Special/海角阁.cs")
    add(268, "揽雀阁", "Special", "Content/Items/Special/揽雀阁.cs")
    add(269, "落英馆", "Special", "Content/Items/Special/落英馆.cs")
    add(270, "烽火台", "Special", "Content/Items/Special/烽火台.cs")
    add(271, "飞沙阁", "Special", "Content/Items/Special/飞沙阁.cs")
    add(272, "送生庙", "Special", "Content/Items/Special/送生庙.cs")
    add(273, "风满楼", "Special", "Content/Items/Special/风满楼.cs")
    add(274, "角连营", "Special", "Content/Items/Special/角连营.cs")

    # 阶段9c - 太古生物
    add(275, "太古上极天鹰", "Special", "Content/Items/Special/太古上极天鹰.cs")
    add(276, "太古之光", "Special", "Content/Items/Special/太古之光.cs")
    add(277, "太古墟蝠尸体", "Special", "Content/Items/Special/太古墟蝠尸体.cs")
    add(278, "太古年兽", "Special", "Content/Items/Special/太古年兽.cs")
    add(279, "太古石龙", "Special", "Content/Items/Special/太古石龙.cs")
    add(280, "太古虎形年兽", "Special", "Content/Items/Special/太古虎形年兽.cs")
    add(281, "太古魂核", "Special", "Content/Items/Special/太古魂核.cs")
    add(282, "万年斗飞车", "Special", "Content/Items/Special/万年斗飞车.cs")
    add(283, "万里丝廊", "Special", "Content/Items/Special/万里丝廊.cs")
    add(284, "万里口蚯", "Special", "Content/Items/Special/万里口蚯.cs")
    add(285, "事实浮冰", "Special", "Content/Items/Special/事实浮冰.cs")
    add(286, "云凰碎片", "Special", "Content/Items/Special/云凰碎片.cs")
    add(287, "惊鸿乱斗台", "Special", "Content/Items/Special/惊鸿乱斗台.cs")
    add(288, "旱魃炎", "Special", "Content/Items/Special/旱魃炎.cs")
    add(289, "深海闪电鳗鱼", "Special", "Content/Items/Special/深海闪电鳗鱼.cs")
    add(290, "生死鲲鹏", "Special", "Content/Items/Special/生死鲲鹏.cs")
    add(291, "苍蓝龙鲸", "Special", "Content/Items/Special/苍蓝龙鲸.cs")
    add(292, "幽冥水母", "Special", "Content/Items/Special/幽冥水母.cs")
    add(293, "定真树", "Special", "Content/Items/Special/定真树.cs")
    add(294, "年华池", "Special", "Content/Items/Special/年华池.cs")
    add(295, "幻景园", "Special", "Content/Items/Special/幻景园.cs")
    add(296, "夜壶", "Special", "Content/Items/Special/夜壶.cs")
    add(297, "白荔仙元", "Special", "Content/Items/Special/白荔仙元.cs")
    add(298, "红枣仙元", "Special", "Content/Items/Special/红枣仙元.cs")
    add(299, "鸡笼犬舍", "Special", "Content/Items/Special/鸡笼犬舍.cs")
    add(300, "黄天碎片", "Special", "Content/Items/Special/黄天碎片.cs")
    add(